version: 2

project_name: go-unifi-mcp

before:
  hooks:
    - go run ./scripts/unifi-controller-version.go -out
      .tmp/unifi-controller-version

builds:
  - id: go-unifi-mcp
    main: ./cmd/go-unifi-mcp
    binary: go-unifi-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/claytono/go-unifi-mcp/internal/server.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

brews:
  - name: go-unifi-mcp
    description: MCP server for UniFi Network Controller
    homepage: https://github.com/claytono/go-unifi-mcp
    license: MPL-2.0
    url_template:
      https://github.com/claytono/go-unifi-mcp/releases/download/{{ .Tag }}/{{
      .ArtifactName }}
    directory: Formula
    repository:
      owner: claytono
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: Clayton O'Neill
      email: claytono@users.noreply.github.com
    test: |
      system "#{bin}/go-unifi-mcp", "--help"
    install: |
      bin.install "go-unifi-mcp"

changelog:
  disable: true

release:
  footer: |
    Tool generation target: UniFi Controller {{ trim (mustReadFile ".tmp/unifi-controller-version") }} (from go-unifi {{ trim (mustReadFile ".go-unifi-version") }})

dockers_v2:
  - ids:
      - go-unifi-mcp
    dockerfile: Dockerfile
    images:
      - ghcr.io/claytono/go-unifi-mcp
    tags:
      - "v{{ .Version }}"
      - "{{ if not .IsSnapshot }}latest{{ else }}edge{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description":
        "MCP server for UniFi Network Controller"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "https://github.com/claytono/go-unifi-mcp"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.created": "{{ .Date }}"
