version: "3"

tasks:
  download-fields:
    desc: Download UniFi API field definitions
    deps: [sync-go-unifi]
    vars:
      # UniFi Controller version for field definitions (from go-unifi repo marker)
      UNIFI_VERSION:
        sh: cat .tmp/go-unifi/.unifi-version
    env:
      GOPATH: "{{.ROOT_DIR}}/.go"
      GOMODCACHE: "{{.ROOT_DIR}}/.go/pkg/mod"
      GOCACHE: "{{.ROOT_DIR}}/.go/cache"
    cmds:
      - rm -rf .tmp/fields
      - mkdir -p .tmp/fields
      - cd .tmp/go-unifi && go run ./codegen -version-base-dir ../fields
        {{.UNIFI_VERSION}} -download-only {{.UNIFI_VERSION}}
      - echo "Downloaded field definitions for UniFi {{.UNIFI_VERSION}} to
        .tmp/fields/"

  lint:
    desc: Run linters via pre-commit
    cmds:
      - scripts/lint

  test:
    desc: Run tests
    cmds:
      - go test ./...

  coverage:
    desc: Run tests with coverage and check thresholds
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go-test-coverage --config .testcoverage.yaml

  generate:
    desc: Generate MCP tool handlers from UniFi API specs
    deps: [download-fields]
    env:
      GOPATH: "{{.ROOT_DIR}}/.go"
      GOMODCACHE: "{{.ROOT_DIR}}/.go/pkg/mod"
      GOCACHE: "{{.ROOT_DIR}}/.go/cache"
    cmds:
      - go run ./cmd/mcpgen -fields .tmp/fields -v2 internal/gounifi/v2 -out
        internal/tools/generated
    sources:
      - cmd/mcpgen/**/*.go
      - internal/mcpgen/**/*.go
      - internal/mcpgen/templates/*.tmpl
      - internal/gounifi/v2/*.json
      - .tmp/fields/**/*.json
    generates:
      - internal/tools/generated/*.go

  build:
    desc: Build the binary
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
    cmds:
      - go build -ldflags "-X
        github.com/claytono/go-unifi-mcp/internal/server.Version={{.VERSION}}"
        -o go-unifi-mcp ./cmd/go-unifi-mcp

  run:
    desc: Run the MCP server (requires UNIFI_* env vars)
    deps: [build]
    cmds:
      - ./go-unifi-mcp

  sync-go-unifi:
    desc: Sync codegen from filipowm/go-unifi
    vars:
      VERSION:
        sh: cat .go-unifi-version
      HEADER: |
        // Code vendored from github.com/filipowm/go-unifi/codegen
        // Licensed under MPL-2.0 - https://github.com/filipowm/go-unifi/blob/main/LICENSE
        // DO NOT EDIT - synced via: task sync-go-unifi
        // Source version: {{.VERSION}}
        //nolint:all
    cmds:
      - rm -rf .tmp/go-unifi
      - git clone --depth 1 --branch {{.VERSION}}
        https://github.com/filipowm/go-unifi.git .tmp/go-unifi
      # Preserve README, remove old Go files
      - mkdir -p internal/gounifi
      - find internal/gounifi -name '*.go' -delete
      - find internal/gounifi -name '*.tmpl' -delete
      - find internal/gounifi -name '*.yml' -delete
      - rm -rf internal/gounifi/v2
      # Copy and patch Go files
      - |
        for f in resources.go validation.go customize.go generator.go clients.go utils.go; do
          echo '{{.HEADER}}' | cat - .tmp/go-unifi/codegen/$f | \
          sed 's/^package main$/package gounifi/' > internal/gounifi/$f
        done
      # Copy templates and config
      - cp .tmp/go-unifi/codegen/*.tmpl internal/gounifi/
      - cp .tmp/go-unifi/codegen/customizations.yml internal/gounifi/
      # Copy v2 custom resources
      - cp -r .tmp/go-unifi/codegen/v2 internal/gounifi/
      # Export private functions we need for mcpgen
      - |
        perl -i -pe 's/func buildResourcesFromDownloadedFields/func BuildResourcesFromDownloadedFields/g' internal/gounifi/resources.go
        perl -i -pe 's/buildResourcesFromDownloadedFields\(/BuildResourcesFromDownloadedFields(/g' internal/gounifi/resources.go
        perl -i -pe 's/func buildCustomResources/func BuildCustomResources/g' internal/gounifi/resources.go
        perl -i -pe 's/buildCustomResources\(/BuildCustomResources(/g' internal/gounifi/resources.go
        perl -i -pe 's/buildResourcesFromDownloadedFields\(/BuildResourcesFromDownloadedFields(/g' internal/gounifi/generator.go
        perl -i -pe 's/buildCustomResources\(/BuildCustomResources(/g' internal/gounifi/generator.go
      # Create log.go with logrus logger
      - |
        cat > internal/gounifi/log.go << 'EOF'
        // Code vendored from github.com/filipowm/go-unifi/codegen
        // Licensed under MPL-2.0 - https://github.com/filipowm/go-unifi/blob/main/LICENSE
        // DO NOT EDIT - synced via: task sync-go-unifi

        package gounifi

        import "github.com/sirupsen/logrus"

        var log = logrus.New()
        EOF
      - echo "Synced go-unifi codegen {{.VERSION}}"
